import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/assets/header/Header"
import Footer from "../components/assets/footer/Footer"
import {motion} from 'framer-motion'



export default function Home() {
  return (

    <div className={styles.container}>

      <Head>
        <title>Tragödie Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
      </Head>
      <Header/>

      <main className={styles.home}>
        <div className={styles.home_banner}>
        <Image src ={`/../public/banners/imagem/Banner-1536x864.png`}
          width={1536}
          height={864}
          alt={"Null"}>
          </Image>
        </div>
        <div className={styles.services_menu}>

        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          className={styles.call_to_services}>
          <div className={styles.about_tag}>
            <h3>Branding </h3>
            <div className={styles.standard_btn}>
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
         className={styles.call_to_services}>
          <div className={styles.about_tag}>
            <h3>Branding </h3>
            <div className={styles.standard_btn}>
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          className={styles.call_to_services}>
          <div className={styles.services_tag}>
            <h3>Branding </h3>
            <div className={styles.standard_btn}>
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          className={styles.call_to_services}>
          <div className={styles.services_tag}>
            <h3>Branding </h3>
            <div className={styles.standard_btn}>
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          className={styles.call_to_services}>
          <div className={styles.services_tag}>
            <h3>Branding </h3>
            <div className={styles.standard_btn}>
            Clique aqui
            </div>
            </div>
          </motion.div>
        </div>

        <div className={styles.call_to_about}>

        <h3> DESIGN PARA
ATINGIR NOVOS PATAMARES</h3>
          <p>Peças de design criadas com compromisso, seriedade e respeitando a sua identidade visual, pois a linguagem do seu negócio é muito importante, e o design atrativo devem andar lado a lado com a sua marca.
          </p>
      <motion.div
        animate={{scale:1}}
        whileHover={{scale:1.3}} className={styles.standard_btn}>
        Conheça
      </motion.div>


        </div>


  </main>
    <Footer/>


    </div>
  )
}
